import { NextRequest, NextResponse } from "next/server";
import { sendSmtpEmail } from "@/lib/smtp-email";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { userEmail, report, symptoms, userContext } = body;

    if (!userEmail || !report) {
      return NextResponse.json({ error: "Email and report are required" }, { status: 400 });
    }

    // Create HTML email template for the medical report
    const subject = 'Your Medical Consultation Report - Onestep Medical Voice AI';
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 800px; margin: 0 auto; padding: 20px; }
          .header { background-color: #0F766E; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
          .content { background-color: #f8f9fa; padding: 20px; border: 1px solid #e9ecef; border-top: none; border-radius: 0 0 8px 8px; }
          .section { margin-bottom: 20px; }
          .section-title { font-size: 18px; font-weight: bold; color: #0F766E; margin-bottom: 10px; }
          .info-item { margin-bottom: 8px; }
          .symptoms { background-color: #e8f4f8; padding: 15px; border-left: 4px solid #0F766E; margin: 15px 0; }
          .report-content { white-space: pre-wrap; background-color: white; padding: 15px; border-radius: 4px; border: 1px solid #ddd; }
          .footer { margin-top: 20px; font-size: 12px; color: #666; text-align: center; }
          .disclaimer { background-color: #fff3cd; border: 1px solid #ffeaa7; padding: 15px; border-radius: 4px; margin-top: 20px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>🏥 Onestep Medical Voice AI</h1>
            <p>Your Personal Health Consultation Report</p>
          </div>
          
          <div class="content">
            <div class="section">
              <div class="section-title">📋 Patient Information</div>
              ${userContext?.age ? `<div class="info-item"><strong>Age:</strong> ${userContext.age}</div>` : ''}
              ${userContext?.gender ? `<div class="info-item"><strong>Gender:</strong> ${userContext.gender}</div>` : ''}
              ${userContext?.height ? `<div class="info-item"><strong>Height:</strong> ${userContext.height}</div>` : ''}
              ${userContext?.weight ? `<div class="info-item"><strong>Weight:</strong> ${userContext.weight}</div>` : ''}
              ${userContext?.conditions ? `<div class="info-item"><strong>Known Conditions:</strong> ${userContext.conditions}</div>` : ''}
            </div>

            <div class="section">
              <div class="section-title">💬 Reported Symptoms</div>
              <div class="symptoms">
                <div style="font-style: italic;">"${symptoms}"</div>
              </div>
            </div>

            <div class="section">
              <div class="section-title">📝 Medical Guidance Report</div>
              <div class="report-content">${report}</div>
            </div>

            <div class="disclaimer">
              <strong>⚠️ Important Disclaimer:</strong>
              <p>This report provides general health information and wellness guidance only. It is not a medical diagnosis, prescription, or substitute for professional medical care. Always consult with qualified healthcare providers for medical concerns and emergencies.</p>
            </div>

            <div class="footer">
              <p>Generated by Onestep Medical Voice AI on ${new Date().toLocaleDateString()}</p>
              <p>This is an automated report. For any concerns about your health, please contact a healthcare professional.</p>
            </div>
          </div>
        </div>
      </body>
      </html>
    `;

    const result = await sendSmtpEmail(userEmail, subject, html);

    if (result.success) {
      return NextResponse.json({ 
        success: true, 
        message: "Report sent successfully to your email." 
      });
    } else {
      return NextResponse.json({ 
        success: false, 
        error: result.error || "Failed to send report" 
      }, { status: 500 });
    }
  } catch (error: any) {
    console.error("Send report error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to send report" },
      { status: 500 }
    );
  }
}